# Generated by Django 5.1.4 on 2024-12-28 04:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='eligibility',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
