# Generated by Django 5.1.4 on 2024-12-28 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0003_remove_scholarship_title_scholarship_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='scholarship_amount',
            field=models.CharField(default='N/A', max_length=255),
        ),
    ]
