# Generated by Django 5.1.4 on 2024-12-28 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0004_alter_scholarship_scholarship_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='grade_s1_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='grade_s2_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='grade_s3_status',
            field=models.BooleanField(default=False),
        ),
    ]
