# Generated by Django 5.1.4 on 2024-12-29 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0005_scholarship_grade_s1_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarship',
            name='discipline',
        ),
    ]
