# Generated by Django 5.1.4 on 2024-12-17 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='industry',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
