# Generated by Django 5.1.4 on 2024-12-27 22:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_job_description_alter_job_qualifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='benefits',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
