# Generated by Django 5.1.4 on 2024-12-27 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_job_benefits'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='apply_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='apply_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
