# Generated by Django 5.1.2 on 2024-11-26 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_remove_news_author_news_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='category',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='news_item',
        ),
        migrations.RemoveField(
            model_name='news',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='newstag',
            name='news_item',
        ),
        migrations.RemoveField(
            model_name='newstag',
            name='tag',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='News',
        ),
        migrations.DeleteModel(
            name='NewsTag',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
