# Generated by Django 5.1.3 on 2024-12-08 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_category_unique_slug_constraint'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='category',
            name='unique_slug_constraint',
        ),
    ]
