# Generated by Django 5.1.3 on 2024-12-08 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_remove_category_unique_slug_constraint'),
    ]

    operations = [
    ]
