# Generated by Django 5.1.3 on 2024-12-08 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20241208_0652'),
    ]

    operations = [
    ]
