# Generated by Django 5.1.3 on 2024-12-08 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_auto_20241208_0654'),
    ]

    operations = [
    ]
