# Generated by Django 5.1.3 on 2024-12-08 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_auto_20241208_0658'),
    ]

    operations = [
    ]
