# Generated by Django 5.1.2 on 2024-12-10 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_alter_newsarticle_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
