# Generated by Django 5.1.2 on 2024-12-12 11:38

import news.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0018_newsarticle_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, validators=[news.models.validate_unicode]),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='author',
            field=models.CharField(max_length=255, validators=[news.models.validate_unicode]),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='title',
            field=models.CharField(max_length=255, validators=[news.models.validate_unicode]),
        ),
    ]
