# Generated by Django 5.1.4 on 2024-12-14 16:57

import ckeditor.fields
import django.db.models.deletion
import tutorial.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, validators=[tutorial.models.validate_unicode])),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(max_length=100, unique=True, validators=[tutorial.models.validate_unicode])),
                ('order', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, validators=[tutorial.models.validate_unicode])),
                ('slug', models.SlugField(max_length=100, validators=[tutorial.models.validate_unicode])),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='tutorial.category')),
            ],
            options={
                'unique_together': {('slug', 'category')},
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, validators=[tutorial.models.validate_unicode])),
                ('slug', models.SlugField(max_length=100, validators=[tutorial.models.validate_unicode])),
                ('content', ckeditor.fields.RichTextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('publish', 'Publish')], default='draft', max_length=10)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='tutorial.category')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='tutorial.subcategory')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('subcategory', 'slug'), name='unique_slug_in_subcategory')],
            },
        ),
    ]
