# Generated by Django 5.1.4 on 2024-12-23 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['order']},
        ),
    ]
