# Generated by Django 5.1.4 on 2024-12-24 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0003_article_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
    ]
