"""
Django settings for Merdeka project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-oq%m*^-8ro5q0+871wce#2a_@$42sx!p705ua^hznt-9gu))h0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['82.112.234.38',www.w3indonesia.com]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    

    'tutorial',
    'ckeditor',
    'ckeditor_uploader',
    'dal',
    'dal_select2',
    'bootcamp',
    'home',
    'news',
    'scholarship',
    'jobs',
    'contact',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Merdeka.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Merdeka.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'w3indonesia_db',
        'USER': 'endo',
        'PASSWORD': 'Merdeka2021',
        'HOST': '82.112.234.38',
        'PORT': '5432',
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR / 'static',)  # This tells Django where to look for additional static files
]

STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

####################################
    ##  CKEDITOR CONFIGURATION ##
####################################

CKEDITOR_JQUERY_URL = 'https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js'

CKEDITOR_UPLOAD_PATH = 'uploads/'
CKEDITOR_IMAGE_BACKEND = "pillow"
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': [
            # Group 1 - Basic formatting
            ['Bold', 'Italic', 'Underline', 'Strike', '-', 'Link', 'Unlink', '-', 'CodeSnippet'],
            
            # Group 2 - List and indentation
            ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent'],
            
            # Group 3 - Alignment and other styling
            ['JustifyLeft', 'JustifyCenter', 'JustifyRight', '-', 'Font', 'FontSize', '-', 'TextColor', 'BGColor'],
            
            # Group 4 - Insert and media
            ['Image', 'Table', 'HorizontalRule', 'Smiley', '-', 'SpecialChar'],
            
            # Group 5 - Undo, redo, and source view
            ['Undo', 'Redo', '-', 'Source'],

            # Group 6 - Markdown-related tools
            ['Blockquote', 'Styles'],
        ],
        'height': 300,
        'width': '100%',
        'extraPlugins': ['codesnippet'],  # Ensure the CodeSnippet plugin is loaded
        'codeSnippet_theme': 'monokai',  # Optional: Use a syntax highlighting theme for code snippets
        'enterMode': 2,  # CKEDITOR.ENTER_BR for <br> line breaks instead of <p> tags
        'shiftEnterMode': 1,  # CKEDITOR.ENTER_P for <p> tags on shift-enter
        'allowedContent': True,  # Allows all HTML tags and attributes
        'extraAllowedContent': 'pre code',  # Allow pre/code tags specifically
    },
}

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR / 'media')

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'ERROR',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'error.log',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'ERROR',
            'propagate': True,
        },
    },
}
